/**
 * ms-supplier-search
 * Supplier Search Microservice
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * Contact: destimo-dev@lists.tui.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Message {
    code?: string;
    level?: Message.LevelEnum;
    localizedText?: string;
    text?: string;
}
export namespace Message {
    export type LevelEnum = 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';
    export const LevelEnum = {
        DEBUG: 'DEBUG' as LevelEnum,
        INFO: 'INFO' as LevelEnum,
        WARN: 'WARN' as LevelEnum,
        ERROR: 'ERROR' as LevelEnum
    };
}
