/**
 * ms-supplier-search
 * Supplier Search Microservice
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * Contact: destimo-dev@lists.tui.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SupplierSearchResultEntry {
    complianceStatus?: string;
    country?: string;
    dateComplianceLastChecked?: Date;
    highlights?: { [key: string]: Array<string>; };
    id?: string;
    name?: string;
    negotiationGroupLabel?: string;
    registrationNr?: string;
    supplierStatus?: string;
    taxNumber?: string;
}
