/**
 * ms-supplier-search
 * Supplier Search Microservice
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * Contact: destimo-dev@lists.tui.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SupplierSearchResultEntry } from './supplierSearchResultEntry';


export interface SupplierSearchResult {
    page?: number;
    pageSize?: number;
    results?: Array<SupplierSearchResultEntry>;
    totalEntries?: number;
    totalPages?: number;
}
